# makefile

# Download "s3.json" definition files of Java and Rust.  Both are for
# Smithy-2.0.  They are virtually identical, differ very slightly.

download-java-s3.json::
	wget https://raw.githubusercontent.com/smithy-lang/smithy-java/refs/heads/main/aws/client/aws-client-rulesengine/src/shared-resources/software/amazon/smithy/java/aws/client/rulesengine/s3.json

download-rs-s3.json::
	wget https://raw.githubusercontent.com/smithy-lang/smithy-rs/refs/heads/main/aws/sdk/aws-models/s3.json
